name       : sdl2-gfx
version    : 1.0.1
release    : 3
source     :
    - https://sourceforge.net/projects/sdl2gfx/files/SDL2_gfx-1.0.1.tar.gz/download : d69bcbceb811b4e5712fbad3ede737166327f44b727f1388c32581dbbe8c599a
license    : zlib
component  : multimedia.library
summary    : SDL2 graphics drawing primitives and other support functions
description: |
    SDL2 graphics drawing primitives and other support functions
builddeps  :
    - pkgconfig(sdl2)
    - pkgconfig32(sdl2)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
