name       : SDL2_gfx
version    : 1.0.1
release    : 1
source     :
    - http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.1.tar.gz : d69bcbceb811b4e5712fbad3ede737166327f44b727f1388c32581dbbe8c599a
license    : GPL-2.0 # CHECK ME
summary    : SDL2 graphics drawing primitives and other support functions 
description: |
    SDL2 graphics drawing primitives and other support functions
builddeps  :
        - pkgconfig(sdl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
